namespace CGPFE.World.Settlement;

public enum Disadvantage {
	ANARCHY,
	ATHEISTIC,
	BUREAUCRATICNIGHTMARE,
	CURSED,
	FASCISTIC,
	HEAVILYTAXED,
	HUNTED,
	IGNORANT,
	IMPOVERISHED,
	MAGICALLYDEADENED,
	MAGICALDEADZONE,
	MARTIALLAW,
	MUTAGENIC,
	OPPRESSED,
	PLAGUED,
	RAMPANTINFLATION,
	SOULCRUSHING,
	POLLUTED,
	WILDMAGICZONE
}